_entry = unitDefs select _m2a2W; _entry set [udModel, "M2A2_MF_xj400"]; unitTypeArray set [_m2a2W, "M2A2_MF_xj400"]; _entry set [udName, "M2A2"]; _entry set [udCost, 1300]; _entry set [udBuildTime, 40]; _entry set [udScripts, []];
_entry = unitDefs select _m3a2W; _entry set [udModel, "M3A2_MF_xj400"]; unitTypeArray set [_m3a2W, "M3A2_MF_xj400"]; _entry set [udName, "M3A2"]; _entry set [udCost, 1500]; _entry set [udBuildTime, 40]; _entry set [udFactoryType, 2^stHeavy]; _entry set [udScripts, []];
_entry = unitDefs select _m60W; _entry set [udModel, "M60_MF_xj400"]; unitTypeArray set [_m60W, "M60_MF_xj400"]; _entry set [udName, "M60"]; _entry set [udCost, 1000]; _entry set [udBuildTime, 40];
_entry = unitDefs select _m60A3W; _entry set [udModel, "M60A3_MF_xj400"]; unitTypeArray set [_m60A3W, "M60A3_MF_xj400"]; _entry set [udName, "M60A3"]; _entry set [udCost, 1400]; _entry set [udBuildTime, 40]; _entry set [udFactoryType, 2^stHeavy];
_entry = unitDefs select _m1a1W; _entry set [udModel, "M1_MF_xj400"]; unitTypeArray set [_m1a1W, "M1_MF_xj400"]; _entry set [udName, "M1"]; _entry set [udCost, 3000]; _entry set [udBuildTime, 50];
_entry = unitDefs select _m1a2sepW; _entry set [udModel, "M1A1_MF_xj400"]; unitTypeArray set [_m1a2sepW, "M1A1_MF_xj400"]; _entry set [udName, "M1A1"]; _entry set [udCost, 4000]; _entry set [udBuildTime, 50]; _entry set [udImage, "iabrams"]; _entry set [udFactoryType, 2^stHeavy];

_entry = unitDefs select _bmpE; _entry set [udModel, "BMP1_MF_xj400"]; unitTypeArray set [_bmpE, "BMP1_MF_xj400"]; _entry set [udName, "BMP"]; _entry set [udCost, 1000]; _entry set [udBuildTime, 35]; _entry set [udScripts, []];
_entry = unitDefs select _bmp2E; _entry set [udModel, "BMP2_MF_xj400"]; unitTypeArray set [_bmp2E, "BMP2_MF_xj400"]; _entry set [udName, "BMP2"]; _entry set [udCost, 1300]; _entry set [udBuildTime, 40]; _entry set [udScripts, []];
_entry = unitDefs select _bmp2_EE; _entry set [udModel, "BMP2E_MF_xj400"]; unitTypeArray set [_bmp2_EE, "BMP2E_MF_xj400"]; _entry set [udName, "BMP2E"]; _entry set [udCost, 1500]; _entry set [udBuildTime, 40]; _entry set [udFactoryType, 2^stHeavy]; _entry set [udScripts, []];
_entry = unitDefs select _t72E; _entry set [udModel, "T72_MF_xj400"]; unitTypeArray set [_t72E, "T72_MF_xj400"]; _entry set [udName, "T72"]; _entry set [udCost, 1700]; _entry set [udBuildTime, 40];
_entry = unitDefs select _t72_AE; _entry set [udModel, "T72A_MF_xj400"]; unitTypeArray set [_t72_AE, "T72A_MF_xj400"]; _entry set [udName, "T72A"]; _entry set [udCost, 1900]; _entry set [udBuildTime, 40]; _entry set [udFactoryType, 2^stHeavy];
_entry = unitDefs select _t72_BE; _entry set [udModel, "T72B_MF_xj400"]; unitTypeArray set [_t72_BE, "T72B_MF_xj400"]; _entry set [udName, "T72B"]; _entry set [udCost, 2200]; _entry set [udBuildTime, 40]; _entry set [udFactoryType, 2^stHeavy];
_entry = unitDefs select _t80E; _entry set [udModel, "T80_MF_xj400"]; unitTypeArray set [_t80E, "T80_MF_xj400"]; _entry set [udName, "T80"]; _entry set [udCost, 2600]; _entry set [udBuildTime, 50];
_entry = unitDefs select _t90E; _entry set [udModel, "T80B_MF_xj400"]; unitTypeArray set [_t90E, "T80B_MF_xj400"]; _entry set [udName, "T80B"]; _entry set [udCost, 3000]; _entry set [udBuildTime, 50]; _entry set [udImage, "it80"]; _entry set [udFactoryType, 2^stHeavy];
_entry = unitDefs select _ztz99E; _entry set [udModel, "T80U_MF_xj400"]; unitTypeArray set [_ztz99E, "T80U_MF_xj400"]; _entry set [udName, "T80U"]; _entry set [udCost, 3400]; _entry set [udBuildTime, 50]; _entry set [udImage, "it80"]; _entry set [udFactoryType, 2^stHeavy];