startPosMode = param1;
Allow_BOH_WAP_TZK = false;
Incomex = 1;
restanksx = param2 + 1;
timeLimit = 4*60*60;
if (bool_TZK_DEV_FPS) then {timeLimit = 0};
maxGroupSize = 12;
WeatherChosen = 0;
ZeroTime = 0;
viewDistance = 1300;
PricingMode = 0;
setViewDistance viewDistance;